### ISSUE TITLE
Angular 11.2.5 support

### ISSUE THREAD

**Issue by dmitry-bas** [danielmoncada/date-time-picker#112]
UnhandledPromiseRejectionWarning: Error: Symbol OwlDateTimeModule declared in /Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@danielmoncada/angular-datetime-picker/lib/date-time/date-time.module.d.ts is not exported from @danielmoncada/angular-datetime-picker (import into /Users/dbas/WebstormProjects/DNOR/src/web-app/src/app/common/common.module.ts)
    at AbsoluteModuleStrategy.emit (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:171:23)
    at ReferenceEmitter.emit (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:251:18)
    at NgModuleDecoratorHandler._toR3Reference (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:490:31)
    at /Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:264:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:264:38)
    at TraitCompiler.analyzeTrait (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:361:40)
    at analyze (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:312:58)
    at _loop_1 (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:334:21)
    at TraitCompiler.analyzeClass (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:340:35)
    at visit (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:110:27)
    at visitNodes (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/typescript/lib/typescript.js:27037:30)
    at Object.forEachChild (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/typescript/lib/typescript.js:27275:24)
    at visit (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:112:20)
    at TraitCompiler.analyze (/Users/dbas/WebstormProjects/DNOR/src/web-app/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:114:13)

**Comment by danielmoncada** [comment]
12 is out. https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker/v/12.0.0
