### ISSUE TITLE
ERROR TypeError: Cannot read properties of null (reading 'clampDate')

### ISSUE THREAD

**Issue by Kartax** [danielmoncada/date-time-picker#197]
I cannot get the very basic input to work in my Angular 17 Application.

template:

`<mat-form-field appearance="outline">`
`  <mat-label>Gültig ab</mat-label>`
`  <input matInput formControlName="validfrom" [owlDateTime]="validfromDt" [owlDateTimeTrigger]="validfromDt">`
`  <owl-date-time #validfromDt></owl-date-time>`
`</mat-form-field>`

and i have `OwlDateTimeModule, OwlNativeDateTimeModule` in my imports.

When i view my form everything looks fine, but when i click into the datetime-input it "tries" to render the calender, but fails with following error:

> core.mjs:6531  ERROR TypeError: Cannot read properties of null (reading 'clampDate')
>     at set pickerMoment (danielmoncada-angular-datetime-picker.mjs:3670:53)
>     at _OwlDateTimeContainerComponent.initPicker (danielmoncada-angular-datetime-picker.mjs:3892:10)
>     at _OwlDateTimeContainerComponent.ngAfterContentInit (danielmoncada-angular-datetime-picker.mjs:3758:10)

When i continue to click, i see a partially rendered calendar and even more but similar errors (Cannot read properties of null ...)
<img width="435" alt="image" src="https://github.com/danielmoncada/date-time-picker/assets/24891257/e67dd3a7-6586-440d-809a-701b7f2223eb">

Does somebody have an idea how to solve this?

**Comment by ChiluBhushan** [comment]
Hi, it looks like it's a compiler error since OwlNativeDateTimeModule & OwlDateTimeModule are not considered ngModule classes since ng-pick-datetime is not compatible with Ivy in angular 17.
I'll recommend using mat-datepicker as they have good UI and are compatible with the latest angular version.

`<mat-form-field>
  <input matInput [matDatepicker]="picker" placeholder="Choose a date">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
`

**Comment by ChiluBhushan** [comment]
ok then try this, this gives date and time and the same UI too
[Material date time picker](https://www.npmjs.com/package/@angular-material-components/datetime-picker)

**Comment by Kartax** [comment]
That is the one that does not work with Angular 17

**Comment by NetWin** [comment]
Heyho @Kartax, i just had a look at this and the demo application has basically the same setup as your code example but it works without any hickups there. See: https://github.com/NetWin/date-time-picker/blob/master/src/app/app.component.html#L22-L36

Can you provide a full example that shows this error? (Stackblitz maybe)

I also tried to use (almost) exactly the code you posted above (i only removed the angular material components / directives) and it works. 
![image](https://github.com/danielmoncada/date-time-picker/assets/7582077/80e349b4-03de-4aa3-a4da-5256cbaddb49)
![image](https://github.com/danielmoncada/date-time-picker/assets/7582077/a20f4d12-7d5b-4b0f-acd2-94894e7a9a01)

**Comment by chrissupnet29** [comment]
I'm having this issue too. Has anyone solved this?

```
<mat-form-field class="w-full" appearance="outline">
    <mat-label>Start Date</mat-label>
        <input
            matInput
            formControlName="startDate"
            [owlDateTime]="sDate"
            [owlDateTimeTrigger]="sDate"
            [selectMode]="'single'"
        >
        <span [owlDateTimeTrigger]="sDate"><mat-icon fontIcon="calendar_today"></mat-icon></span>

        <owl-date-time #sDate>></owl-date-time>
</mat-form-field>
```

![image](https://github.com/user-attachments/assets/23166d3f-a541-4e42-8b36-58ae5e2e31cb)

I tried adding break points on the line with errors and it seems like the `this.dateTimeAdapter` is` null`

![image](https://github.com/user-attachments/assets/83678bee-397d-40bc-b5ac-5ca769fc843b)

**Comment by SergioV85** [comment]
Thank you, @Toso7, for your suggestion. I had the same problem with my code, and I was able to solve it using your solution.
Also, I had a problem with formats, so I solved it by adding:
`{ provide: OWL_DATE_TIME_FORMATS, useValue: MY_OWL_FORMATS },` 
to `providers` in components.

`MY_OWL_FORMATS` I've just copied from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by Toso7** [comment]
@SergioV85  Yes I already use custom owl formats.

I had another problem: Cannot display multiyear picker in material dialog.  I fixed it with this: 

` {
            provide: OptionsTokens.multiYear,
            useFactory: multiYearOptionsFactory,
            deps: [OptionsTokens.all],
        }`
        
I hope that I save somebody's time :D

**Comment by NicmeisteR** [comment]
> @chrissupnet29 I had same issue in dialog component, I resolved it by
> 
> ` providers: [ { provide: DateTimeAdapter, useClass: NativeDateTimeAdapter, }, ]`

This also fixed it for me! Thanks.
