### ISSUE TITLE
Problem with ngModel and owl-date-time-inline

### ISSUE THREAD

**Issue by FilipaAlves** [danielmoncada/date-time-picker#52]
Hello, 

I have one problem when I put ngModel . I have this in my HTML:
<owl-date-time-inline [startAt]="todayDate"
                                              pickerType="calendar"
                                             [(ngModel)]="selectedMoment"
                                              name="calender"
                                              (ngModelChange)="dateChanged($event)"
                                              [ngModelOptions]="{standalone: true}"
                                              effectBoxShadow="off"
                                              effectBackground="off">
                        </owl-date-time-inline>

And I have this error:
ERROR NullInjectorError: R3InjectorError(AppModule)[NgForm -> NgForm -> NgForm]: 
  NullInjectorError: No provider for NgForm!
    at NullInjector.get (https://localhost:44305/vendor.js:39899:27)
    at R3Injector.get (https://localhost:44305/vendor.js:53893:33)
    at R3Injector.get (https://localhost:44305/vendor.js:53893:33)
    at R3Injector.get (https://localhost:44305/vendor.js:53893:33)
    at NgModuleRef$1.get (https://localhost:44305/vendor.js:71194:33)
    at Object.get (https://localhost:44305/vendor.js:68928:35)
    at getOrCreateInjectable (https://localhost:44305/vendor.js:43701:39)
    at ɵɵdirectiveInject (https://localhost:44305/vendor.js:57708:12)
    at ɵɵinject (https://localhost:44305/vendor.js:39764:57)
    at injectArgs (https://localhost:44305/vendor.js:39881:23)
defaultErrorLogger @ core.js:6228
core.js:6228 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[NgForm -> NgForm -> NgForm]: 
  NullInjectorError: No provider for NgForm!
NullInjectorError: R3InjectorError(AppModule)[NgForm -> NgForm -> NgForm]: 
  NullInjectorError: No provider for NgForm!
    at NullInjector.get (core.js:1085)
    at R3Injector.get (core.js:16955)
    at R3Injector.get (core.js:16955)
    at R3Injector.get (core.js:16955)
    at NgModuleRef$1.get (core.js:36329)
    at Object.get (core.js:33972)
    at getOrCreateInjectable (core.js:5848)
    at ɵɵdirectiveInject (core.js:21103)
    at ɵɵinject (core.js:950)
    at injectArgs (core.js:1067)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)

Thank you for your attention, 
Filipa

**Comment by danielmoncada** [comment]
no updates in over 3 months from OP.. abandoning
